### PR TITLE
Publishers send the latest shared value for new subscriptions.

### LINKED ISSUE #160: New subscribers to `State.publisher` receiving old value
### Description

At the time of writing, the [current implementation of `Sharing.publisher` on `main`](https://github.com/pointfreeco/swift-sharing/blob/8f8fef0279ed6e71a166cedc870dcd422bb24a6c/Sources/Sharing/SharedPublisher.swift) looks like this:
```
    public var publisher: some Publisher<Value, Never> {
      box.subject
        .handleEvents(receiveSubscription: { [box] _ in _ = box })
        .prepend(wrappedValue)
    }
```

I approached this API expecting new subscribers to the returned publisher would receive the latest shared value. However, new subscribers receive the shared value at the time the publisher was created. Those new subscribers will receive the next shared value after. To my mind, this behaviour is counterintuitive.

My use cases are features subscribing and unsubscribing from the same publisher when their views appear and disappear.

### Checklist

- [x] I have determined whether this bug is also reproducible in a vanilla SwiftUI project.
- [x] If possible, I've reproduced the issue using the `main` branch of this package.
- [x] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/pointfreeco/swift-sharing/issues) or [discussion](https://github.com/pointfreeco/swift-sharing/discussions).

### Expected behavior

New subscribers receive the latest shared value.

### Actual behavior

New subscribers receive the shared value at the time the publisher was created.

### Reproducing project

Add the test below to `PublisherTests.swift`. The failure associated with the second subscription demonstrates the problem.

In this failure, `"initial"` represents the shared value at the time the publisher was created, but `"latest"` is the latest shared value when the second subscription occurs:
```
Expectation failed: (secondSubscriberValues.withLock(\.self) → ["initial", "next"]) == ["latest", "next"]
```

`"next"` represents the value shared after the second subscription.

The test to add:
```
@Test func newSubscribersReceiveLatestValue() async throws {
  @Shared(value: "initial") var value
  let publisher = $value.publisher
  
  let firstSubscriberValues = Mutex<[String]>([])
  
  let firstCancellable = publisher.sink { completion in
    Issue.record()
  } receiveValue: { @Sendable value in
    firstSubscriberValues.withLock { $0.append(value) }
  }
  defer { _ = firstCancellable }
  
  $value.withLock { $0 = "latest" }
  #expect(firstSubscriberValues.withLock(\.self) == ["initial", "latest"])
  
  let secondSubscriberValues = Mutex<[String]>([])
  
  let secondCancellable = publisher.sink { completion in
    Issue.record()
  } receiveValue: { @Sendable value in
    secondSubscriberValues.withLock { $0.append(value) }
  }
  defer { _ = secondCancellable }
  
  $value.withLock { $0 = "next" }
  #expect(secondSubscriberValues.withLock(\.self) == ["latest", "next"])
}
```

### Sharing version information

8f8fef0279ed6e71a166cedc870dcd422bb24a6c

### Destination operating system

iOS 18

### Xcode version information

Version 16.3 (16E140)

### Swift Compiler version information

```shell
swift-driver version: 1.120.5 Apple Swift version 6.1 (swiftlang-6.1.0.110.21 clang-1700.0.13.3)
Target: arm64-apple-macosx15.0
```

### PR DESCRIPTION
**Pull request by kielgillard**
Fixes #160.

At the time of writing, the [current implementation of `Sharing.publisher` on `main`](https://github.com/pointfreeco/swift-sharing/blob/8f8fef0279ed6e71a166cedc870dcd422bb24a6c/Sources/Sharing/SharedPublisher.swift) looks like this:
```
    public var publisher: some Publisher<Value, Never> {
      box.subject
        .handleEvents(receiveSubscription: { [box] _ in _ = box })
        .prepend(wrappedValue)
    }
```

I approached this API expecting new subscribers of the returned publisher to receive the latest shared value. However, new subscribers receive the shared value at the time the publisher was created. Those new subscribers will receive the next shared value after. To my mind, this behaviour is counterintuitive.

Please see #160 for more detail.

Slack thread: https://pointfreecommunity.slack.com/archives/C0837DJJFA9/p1746759794786839

### CODE REVIEW

File: Sources/Sharing/SharedPublisher.swift [hunk 1]
```diff
@@ -15,9 +15,9 @@
     /// }
     /// ```
     public var publisher: some Publisher<Value, Never> {
-      box.subject
-        .handleEvents(receiveSubscription: { [box] _ in _ = box })
-        .prepend(wrappedValue)
+      Just<Void>(()).flatMap { _ in
+        box.subject.prepend(wrappedValue)
+      }
```
Comment (pyrtsa) [inline Sources/Sharing/SharedPublisher.swift:20]: AFK now, but I wonder if you could replace this whole thing with just:
```suggestion
     box.reference.publisher
```
?

Comment (kielgillard) [reply Sources/Sharing/SharedPublisher.swift:20]: Also AFK, but I don't think so because the subjects these references have are passthrough subjects, which is why prepending the current value is needed when creating a new publisher.

Comment (pyrtsa) [reply Sources/Sharing/SharedPublisher.swift:20]: If you look at the available implementations for `Reference`-conforming types, you'll find that they already prepend the current value, e.g. https://github.com/pointfreeco/swift-sharing/blob/main/Sources/Sharing/Internal/Reference.swift#L58-L60

Comment (stephencelis) [reply Sources/Sharing/SharedPublisher.swift:20]: @pyrtsa That prepending is there for when you reload a shared with a new projected value and is unrelated to these properties directly on `Shared` (if you try locally you can see which tests will fail).
